package com.wondersgroup.cmc.edata.upload.common;

import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

import com.wondersgroup.cmc.edata.utils.EdataUtils;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * UploadServiceService service = new UploadServiceService();
 * UploadServiceDelegate portType = service.getUploadServicePort();
 * portType.upload(...);
 * </pre>
 * 
 * </p>
 */
@WebServiceClient(name = "UploadServiceService", targetNamespace = EdataUtils.Edata_DEFALUT_NAMESPACE)
public class UploadServiceService extends Service {

	public UploadServiceService(String wsdlLocation) throws Exception {
		super(new URL(wsdlLocation), new QName(EdataUtils.Edata_DEFALUT_NAMESPACE, "UploadServiceService"));
	}

	/**
	 * @return returns UploadServiceDelegate
	 */
	@WebEndpoint(name = "UploadServicePort")
	public UploadServiceDelegate getUploadServicePort() {
		return super.getPort(new QName(EdataUtils.Edata_DEFALUT_NAMESPACE, "UploadServicePort"),
				UploadServiceDelegate.class);
	}

}
