package com.wondersgroup.cmc.edata.upload.common;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

import com.wondersgroup.cmc.edata.upload.model.common.PutRequestData;
import com.wondersgroup.cmc.edata.upload.model.common.PutResponseData;
import com.wondersgroup.cmc.edata.utils.EdataUtils;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390- Generated source version: 2.0
 */
@WebService(name = "UploadServiceDelegate", targetNamespace = EdataUtils.Edata_DEFALUT_NAMESPACE)
public interface UploadServiceDelegate {

	/**
	 * @param arg0
	 * @return returns com.wondersgroup.cmc.upload.PutResponseData
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "upload", targetNamespace = EdataUtils.Edata_DEFALUT_NAMESPACE, className = "com.wondersgroup.cmc.edata.upload.model.base.Upload")
	@ResponseWrapper(localName = "uploadResponse", targetNamespace = EdataUtils.Edata_DEFALUT_NAMESPACE, className = "com.wondersgroup.cmc.edata.upload.model.base.UploadResponse")
	public PutResponseData upload(@WebParam(name = "arg0", targetNamespace = "")
	PutRequestData arg0);

}
